language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: z3onAbl8Zz9unOMLxkBbZtqdZPZua3l5wj5RiI6CXQ45/sXuarPs6H9Q8QbVHZBBAkRAK/Sd/SQQbHRbhKhXJyPPcYGBx+N3SNyudzXICKAMdcD27ODwswlbqNqThB69+gL1jlImunbRuV3ZEqxStnX2AY43hfgUZ3fpNm9IZlw5ImsJbtqxVyuc8eCJ6XUdlNzRNMUvdHnCR140+pxXNWP4uWzqSNcO3YPH22ybpB9BNT+ggJF34CUBxlT9RJg3t0dCLZFx5/PQXeKlSUsbKfezv3rghSEaX+0QPFRmGJwBrxnpeOGzHAmoD3sC8RLiEyl5Be6nD+wWObbnMGIRrB0HGiHSI+Qekjtx/tQf/UYTPT0qLyVqbSGK6l3FmwI7+EvarNrT8TzX0n8BTZ8SmMIDLDNAk4e0AiG8m4pcydssv6tH4JUZ3QSaUsLt8yaqk1hAi7UxRnDETx7GOvM94mxT4wYOe7hsb+jczb+J9FWBuheK1S3WcRp04IsXW39MM5FygQ65g9rEeGJpjXGMrhPO/rhVPCWxT6t7Ttea9PqSJ0IvqU1Oa1EjXApfO9bmlAtmlHKGkoGMfpS+YVXB6haVFmbdlTvXHrsKW+Zq2lmSmyvCYkAuy5ZR9w6eepAeEeT4VKAu0JoOopf06j6mkCLCWDOjO1gQgip+R5rytsQ=
